#!/bin/bash
echo "hello guys"
echo "good evening"
echo "morning"
echo "hello vivek bhai we have to do hard practise"
hi anand how are you !
weare learing  branch1
vivek srivastav
abcdefgh
hwiehklrjlrl
jklmno
