#!/bin/bash
#This is my 1st shell script to print output
echo "Hello All, Welcome to AWS/Devops Class"
echo "Hello, How are you?"
echo "Welcome to Young Minds"
echo "Best class of AWS/DevOps"
echo "We are learning git"
echo "We are done with git"
echo "This example is of branching strategy"
echo "This is my new scripts "
echo " Git and github best solution"
echo " this one new changes"
echo " my new scripts avilable in  github"
echo "Hello Batch-16, We are learning Git/Github"
echo "Good Evening"
echo "We are changing script1"
echo "We have applied this changes in main branch"
