echo "We are trying this practical from linux EC2"
echo "We are from batch-23 and learning git/gihub"
echo "Happy weekend"
echo "we are learning git and github from surja sir"
echo " we will be devops engineer soon"
echo "hi i am learning devops aws cloud"
echo "happy weekend"
echo "i am from batch-23"
