echo "Good Morning"
echo "Welcome"
echo "We are trying this practical from linux EC2"
echo "We are from batch-25 and learning git/gihub"
echo "we are trying practical from Linux"
echo "we are learning branching"
echo "Thankyou Bye"
echo "See you again"
